### ISSUE TITLE
Use the same viewer simultaneously with multiple files.

### ISSUE THREAD

**Issue by RODOBTA** [sayanee/angularjs-pdf#100]
You can load the same value in multiple html files without overwriting the data contained (ie use
a global viewer and to open several at once with direfentes files), so far I've only managed to do one
when opening the second overwrite the first.

**Comment by sayanee** [comment]
Yes, currently multiple html files are not supported.

**Comment by RODOBTA** [comment]
Thank you very much, I will try how to do so using other methods.

**Comment by sayanee** [comment]
thanks @RODOBTA - please feel free to raise a pull request to add to the `readme.md` if it works for you :+1:
