### ISSUE TITLE
Support angular 1.4.9

### ISSUE THREAD

**Issue by normanjaeckel** [sayanee/angularjs-pdf#103]
It's just about using `"angular": "~1.4.8"` instead of `"angular": "1.4.8"`so my project can use e. g. version 1.4.9 without bower complaining about possible version conflicts.

Thank you very much.

**Comment by sayanee** [comment]
Refer to #58 - you can use [bower resolutions](https://github.com/bower/spec/blob/master/json.md#resolutions). Feel free to re-open issues if this did not work.
