### ISSUE TITLE
Loading Local Files

### ISSUE THREAD

**Issue by ppeetteerrs** [sayanee/angularjs-pdf#104]
May I ask if ng-pdf works with pdfUrl in the form of file:///storage/emulated/0/pdf/test.pdf ? From what I see there seems to be a xhr error when I do this. Thank You!

**Comment by sayanee** [comment]
You will need to serve the file in a server and hence a `url`. It cannot use a static file link.

**Comment by ppeetteerrs** [comment]
But is it possible to convert it into unit8array and use the raw data as the pdfUrl?

**Comment by sayanee** [comment]
@ppeetteerrs [yes it is](https://github.com/sayanee/angularjs-pdf#when-url-is-base64-or-uint8array)
