### ISSUE TITLE
Worker Disabled?

### ISSUE THREAD

**Issue by brandonkboswell** [sayanee/angularjs-pdf#107]
I just noticed in the Link function of Angular-PDF that you call PDFJS.disableWorker. Is there is a specific reason you are explicitly disabling this?

Thank you for this fantastic library!

**Comment by sayanee** [comment]
No specific reason - do you need it to be enabled? Maybe we can pass it in as an option.

To refresh myself, I'm also looking at the [pdf.js code examples and in the comments](https://github.com/mozilla/pdf.js/search?utf8=%E2%9C%93&q=disableWorker) I see some reasons stated not disabling it.

**Comment by brandonkboswell** [comment]
I don't **need** it, they just cite better/non-blocking performance in supported browsers with it enabled. I just wanted to make sure there wasn't a known issue that prevented it from being enabled. I've been running it since yesterday with it enabled and have not seen any issues.

**Comment by sayanee** [comment]
Thanks for checking it in use. Please feel free to close this issue then 🤗
