### ISSUE TITLE
Warning: Unhandled rejection: Error: Worker task was terminated

### ISSUE THREAD

**Issue by dockinkong** [sayanee/angularjs-pdf#109]
Hello,

I've written a directive to view pdf files in a popup using angularjs-pdf and I'm facing an issue when closing my directive before rendering has completly finished and reopen the popup. In the console I have: 

`cancelled`
`Warning: Unhandled rejection: Error: Worker task was terminated`
`Error: Worker task was terminated`
`at WorkerTask.prototype.ensureNotTerminated (http://localhost:50074/Scripts/pdf/pdf.worker.js:41699:9)`
`at next (http://localhost:50074/Scripts/pdf/pdf.worker.js:37742:9)`
`at Anonymous function (http://localhost:50074/Scripts/pdf/pdf.worker.js:37814:19)`
`at runHandlers (http://localhost:50074/Scripts/pdf/pdf.js:1382:41)`

Reopening the popup let the loading state to 'true' and I cannot get my pdf back in the viewer unless reloading page.

Is there a way to cancel the 'in progress' worker when closing my popup or should I do something else to avoid this issue to happen?

Regards,

**Comment by dennybiasiolli** [comment]
Hello @dockinkong ,
at this moment is not possible to directly stop rendering worker from this directive, but I hope [this link](http://stackoverflow.com/a/18081839/3963422) can help you with this issue.
Nice work! :)
