### ISSUE TITLE
Align 'space beyond border' text with the 'sheraton Puerto ....' text

### ISSUE THREAD

**Issue by jgmboricua** [sayanee/angularjs-pdf#113]
![image](https://cloud.githubusercontent.com/assets/15098174/13831479/afcf7b34-ebb2-11e5-9414-8f52b79b73de.png)

**Comment by sayanee** [comment]
This issue has no reproducible steps. Please re-open this issue if it still occurs, with a JSBin containing a set of reproducible steps. Check this element's CONTRIBUTING.md for an example.
