### ISSUE TITLE
Password Callback

### ISSUE THREAD

**Issue by guicoma** [sayanee/angularjs-pdf#115]
I recently added angularjs-pdf to my project. A great directive! Congrats! However, I've stumbled upon a little problem. I can't seem to find a wave to handle PDF files that have a password.

`PDFJS.getDocument(params, null, null, scope.onProgress);`

Currently there is no handler for the password protected PDFs, one could simply add a scope function so that the controller can handle is case.

`PDFJS.getDocument(params, null, scope.onPassword, scope.onProgress);`

**Comment by dennybiasiolli** [comment]
@guicoma now version 1.4.0 implements your request 😉
