### ISSUE TITLE
it does not work on ie

### ISSUE THREAD

**Issue by eassa** [sayanee/angularjs-pdf#117]
i got this error even on you demo page : https://sayan.ee/angularjs-pdf/

SCRIPT5007: Unable to get property 'src' of undefined or null reference
pdf.js (9172,5)

**Comment by stefan2904** [comment]
which version of IE?

**Comment by eassa** [comment]
all of them !! , if you enter edge it works fine , but if you try to open with internet explorer  virsion 9 - 11 it does not load .

**Comment by sayanee** [comment]
This module has a dependancy on PDF.js. Seems like there's limited support for IE10 and below: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-browsers-are-supported

**Comment by eassa** [comment]
thx , i will look into it :) , but still , internet explorer 10 and 11 does not work either

**Comment by itssujan** [comment]
Yeah it does not work on IE. Any updates on this?

**Comment by jamesone** [comment]
any fix? @itssujan  having the same issue here! A white page shows, I think it's because of DFP ads.

**Comment by eassa** [comment]
i found out some extension for pdfjs and it worked ,can't find it now though , try to update to the latest pdf.js and worker  . they might have fixed the issue
