### ISSUE TITLE
Error during font loading and progress does not work

### ISSUE THREAD

**Issue by sentoro** [sayanee/angularjs-pdf#118]
Hello! In Console i see warning:
"Warning: Error during font loading: this._map[charCode].charCodeAt is not a function  pdf,js:281"
And i see the corrupt fonts http://i.imgur.com/X7D7XPR.png
Also in some documents i see "Warning: Failed to load font "g_d1_f6": SyntaxError: Invalid font data in ArrayBuffer. pdf,js:281"

And progress does not work. I put in controller function "
  $scope.onProgress = function(progress) {
    console.log(progress);
  }"

but in console i can not see anything. Maybe cause in warning "Warning: Deprecated API usage: getDocument is called with pdfDataRangeTransport, passwordCallback or progressCallback argument"

Help please.

**Comment by dennybiasiolli** [comment]
@sentoro is this fixed in v1.3.1 by commits 7da1802 and bef9c64 ?
