### ISSUE TITLE
Package is not available on npm

### ISSUE THREAD

**Issue by craigcabrey** [sayanee/angularjs-pdf#119]
I was searching for the package on npm but couldn't find it. Could you publish it on there please?

Thanks!

**Comment by sayanee** [comment]
This is a frontend package. Not sure if npm would be appropriate for this. I welcome links / documentation on using npm for frontend packages to read up more on this.

Thanks :smiley:

**Comment by craigcabrey** [comment]
npm is widely used for frontend dependencies. [here](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging) is their blog post on the matter.

While there are [questions](https://github.com/aspnet/Home/issues/1074) of bower's continued relevancy, both bower and npm can co-exist, so there is no harm in publishing on npm.

There are many frontend packages available on npm, such as angular, jquery, bootstrap, pdf.js, lots of angular modules, etc.

**Comment by sayanee** [comment]
It's now available in npm: https://www.npmjs.com/package/angular-pdf thanks to @jdw6359 🤗

**Comment by jdw6359** [comment]
I'll happily change ownership (should you ever want it) to you upon your request. Thanks

**Comment by sayanee** [comment]
@jdw6359 no it's cool! Happy to see the community step up and help 😃
