### ISSUE TITLE
Disable controls

### ISSUE THREAD

**Issue by gabrielalfa** [sayanee/angularjs-pdf#120]
Olá

Tem a possibilidade de desativar a barra de controles superior?

Vou utilizar em mobile, portanto o zoom será feito por gestos manuais.

Obrigado

**Comment by sayanee** [comment]
É possível excluir `$scope. getNavStyle` como mostrado no exemplo:

https://github.com/sayanee/angularjs-pdf/blob/be1ab8cf11ddd1c6f2bfb7f7861fb2d758b6f1a5/example/js/controllers/docCtrl.js#L8-L11

spero que isso funciona!

**Comment by gabrielalfa** [comment]
Eu respondi em ingles

Mas na verdade vc é brasileiro?

KKK

Obrigado

2016-04-16 12:26 GMT-03:00 Sayanee Basu <notifications@github.com>:
