### ISSUE TITLE
Ng=If and possible memory issues

### ISSUE THREAD

**Issue by donovan-duplessis** [sayanee/angularjs-pdf#122]
Hey,

I have a generate button to generate a dynamic pdf and display it on my page.  I can re-generate many times.  I use the following:

``` js
<ng-pdf template-url="views/partials/pdf/statement.html" scale="page-fit" page="{{ page }}" ng-show="file!==null && !errored && !loading"></ng-pdf>
```

I think the ng-show (I totally stand under correction here) is not destroying the component properly when I re-generate.  If I generate too many times, it starts taking very long to render the pdf; it starts rendering piece by piece from the top down.  I noticed when I used the page on my phone, after a few generates, eventually when I closed down the browser, my phone hung for a while before responding again.  

I think I could have a memory leak of sorts.  This makes me think I need ng-if instead of ng-show so that the scope can be destroyed.  Yet when I use ng-if the directive doesn't ever display?  Maybe I am way off track here which is highly likely.

In my mind I need to have it destroyed before I re-generate the next PDF.

Any ideas would be greatly appreciated,
Donovan

**Comment by dennybiasiolli** [comment]
Hi @donovan-duplessis ,
I think `ng-if` is destroying the DOM portion of the directive, so the canvas is no longer linked with the directive.
Do you have the same problem with the latest version of angularjs-pdf?

**Comment by smallbitt** [comment]
Hi, 
I'm having same issue with ng-if, at first my pdf get opened, at second I get just blank page.
if I take ng-if directive off (I'm using a modal window) then I get "Cannot read property 'getContext' of null" error.. 
an ideas to make it work?

**Comment by simobasso** [comment]
@smallbitt can you provide a simple jsfiddle?

**Comment by simobasso** [comment]
closed for lack of response
