### ISSUE TITLE
Question: pass the pdf name as parameter

### ISSUE THREAD

**Issue by cataquil** [sayanee/angularjs-pdf#126]
I see this <input type="text" ng-model="pdfUrl">
how can I post the pdf url to the controller

**Comment by sayanee** [comment]
You can pass the url as `$scope.pdfUrl` (see [point 6](https://github.com/sayanee/angularjs-pdf#getting-started)) or even when the url is [base64 or Uint8Array](https://github.com/sayanee/angularjs-pdf#when-url-is-base64-or-uint8array).

**Comment by cataquil** [comment]
but how do I get that parameter into the controller.
