### ISSUE TITLE
Load multiple ng-pdf tags in the same page

### ISSUE THREAD

**Issue by cataquil** [sayanee/angularjs-pdf#131]
Is there a way to have more than 1 viewer in the same page?

**Comment by mayson14** [comment]
just working on figuring out the same thing

**Comment by sayanee** [comment]
Sorry, this is not possible with the current features.

**Comment by cataquil** [comment]
how can I load the 2nd page of a pdf in the viewer programmatically?
Just set $scope.pageNum or $scope.pageToDisplay?

**Comment by sayanee** [comment]
Yes `$scope.pageNum` should do

**Comment by scripterkaran** [comment]
+1

**Comment by ToJuMaLe** [comment]
+1

**Comment by gabrielvilaboa** [comment]
+1

**Comment by bike2live** [comment]
+1
Love the other features, but I need to view 2 pdfs in same page for comparison. Can you point me to what I need to change to make this work?
