### ISSUE TITLE
How to use the ControllerAs syntax

### ISSUE THREAD

**Issue by OscarAgreda** [sayanee/angularjs-pdf#133]
Thank you for sharing. it is nice to see smart and well written code such as this directive.

I was wondering how to use the COntrollerAs syntax.

for example on your sample code

```
<div class="wrapper" ng-controller="DocCtrl">
    <ng-pdf template-url="/partials/viewer.html"></ng-pdf>
</div>
```

how to bind the directive to the controller

```
app.controller('DocCtrl', function($scope) {
    $scope.pdfUrl = '/pdf/relativity.pdf';
});
```

using 

`vm.pdfUrl = '/pdf/relativity.pdf';`

still if not possible, this directive is still super awesome :)

**Comment by davasqueza** [comment]
+1

**Comment by dennybiasiolli** [comment]
Hi @OscarAgreda,
thanks and sorry for the late answer.
Now is not possible to use ControllerAs syntax, because the directive's scope is not isolated.
We are working on a new version that include this feature.
Stay tuned! 😄

**Comment by graspsolutions** [comment]
Very interested in this as well!

**Comment by simobasso** [comment]
dup of #90
