### ISSUE TITLE
Can pages scroll? Is there progress bar?

### ISSUE THREAD

**Issue by chairy11** [sayanee/angularjs-pdf#134]
Hi, I am  trying to use angular-pdf on my ionic APP to display pdf file.  
But I found only by click the previous or next button can lead me to the other page,  that's a little troublesome. 
Is there any setting can make pages like [the official pdf.js](http://mozilla.github.io/pdf.js/web/viewer.html)'s effect? It has vertical scroll bar, I can move to the next page by scrolling my mouse.
And also, there will be a white progress bar on the top of the canvas showing the progress, if angular-pdf has the same effect by some setting?

Thank you very much!

**Comment by sayanee** [comment]
Sorry, currently there is no such setting
