### ISSUE TITLE
Angularjs-pdf does not work on IE

### ISSUE THREAD

**Issue by itssujan** [sayanee/angularjs-pdf#135]
The library does not work on IE11 and has started effecting our app completely. I have gone ahead and disabled the pdf viewer for now untill we have a solution.

The demo site also doesnt work on IE11. Do let us know if there is any idea on this? I will keep looking for solutions from my side too.

Thanks!

**Comment by itssujan** [comment]
Little more info from debugging 

document.currentScript does not work on IE11 and so pdfjs location code does not work

**Comment by udiedrichsen** [comment]
IE11 works for me. 
Check this out:
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-browsers-are-supported

and include the 
https://github.com/mozilla/pdf.js/blob/master/web/compatibility.js

file in your project. Hope that helps.

**Comment by dennybiasiolli** [comment]
@itssujan did you solve your compatibility problem with @udiedrichsen 's solution?
