### ISSUE TITLE
pdf read work in browser but not in mobile device

### ISSUE THREAD

**Issue by santoshshinde2012** [sayanee/angularjs-pdf#136]
I have use the your given template example in my ionic app , it test very well in browser but not in device it shows blank screen.

Why it is happening ?

**Comment by sayanee** [comment]
Please check which browsers are supported for pdf.js: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-browsers-are-supported

**Comment by santoshshinde2012** [comment]
so it is not supported with ionic framework

**Comment by sayanee** [comment]
Which mobile browser are you using?

**Comment by santoshshinde2012** [comment]
this is hybrid based mobile application which is run internally on system webview

**Comment by paolorr** [comment]
I solved this problem changing the reference from pdf.js to pdf.combined.js in the index.html

**Comment by mayank-shekhar** [comment]
this is not working for hybrid mobile applications. This is able to render PDF on android but not able to render pdf on IOS. 

iOS version 9.3
