### ISSUE TITLE
Not working when it is bundled

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [sayanee/angularjs-pdf#137]
This plugin is working fine in the development mode. If i minify the files to serve in the production, then it is not working. And no errors in the logs too.

**Comment by sayanee** [comment]
I'm so sorry, I'm unable to help with out any error logs or any other details 😞 . What is the browser and any browser console error in the client side?

Since it's working in development mode and not in production, I'm guessing it might be related to the intermediate steps?

**Comment by rajeshwarpatlolla** [comment]
There are no errors in the console. And also i am using the gulp-angular seed project for building the app for production environment.

**Comment by Wol** [comment]
I'm seeing a similar issue, and this is a PDFJS issue as far as I can tell. 

In the PDFJS Worker, there's a line of code which has:

```if (pdfjsFilePath) {
      return pdfjsFilePath.replace(/\.js$/i, '.worker.js');
    }```

The `pdfjsFilePath` variable contains the bundled filename e.g. `example.com/js/mybundledfile.js`, not the original `pdf.js`. Consequently, it tries searching for `mybundledfile.worker.js, can't find it, and then bails out.

**Comment by dennybiasiolli** [comment]
Have you tried to include `pdf.combined.js` instead of `pdf.js`?
