### ISSUE TITLE
angularjs-pdf doesn't work with MEAN.js

### ISSUE THREAD

**Issue by damon-kwok** [sayanee/angularjs-pdf#140]
platform MEAN.js 0.4.2
angular: 1.4.12

`
<ng-pdf template-url="/partials/viewer.html" scale=1></ng-pdf>
`
doesn't work

**Comment by simobasso** [comment]
hi @damon-kwok! Can you post the traceback?

**Comment by dennybiasiolli** [comment]
Closed due to no responses, @damon-kwok feel free to reopen this one. 😉
