### ISSUE TITLE
Interpolated templateUrl

### ISSUE THREAD

**Issue by kazupooot** [sayanee/angularjs-pdf#142]
Hi! Is there a way for me to interpolate on `templateUrl` attribute? 

Example:
HTML
`<ng-pdf template-url="{{vm.templateUrl}}" test debug="false" scale="1.6" pdfurl="vm.pdfUrl" canvasid="pdf-canvas"></ng-pdf>`

JS
`
var vm = this;

vm.templateUrl = '/app/views/pdf-control.html?v=' + version;
`

**Comment by simobasso** [comment]
@kazupooot have you tried without curly braces?
like: 
`<ng-pdf template-url="vm.templateUrl" test debug="false" scale="1.6" pdfurl="vm.pdfUrl" canvasid="pdf-canvas"></ng-pdf>`

**Comment by straussCS** [comment]
@simobasso This does not work for me, angularjs-pdf seems to treat both options as string. Dynamically setting the template-url does not work.

**Comment by dennybiasiolli** [comment]
@straussCS have you tried editing our example code inserting your custom template's URL?

**Comment by straussCS** [comment]
@dennybiasiolli I tried with both

`          <ng-pdf template-url="templateUrl" debug="false"></ng-pdf>`
and

`          <ng-pdf template-url="{{templateUrl}}" debug="false"></ng-pdf>`

And in both cases I get a 404:
`Failed to load template: templateUrl (HTTP status: 404 Not Found)`

Please note I am using not using controllerAs, thus no 'vm'.

**Comment by dennybiasiolli** [comment]
@straussCS can you provide an example of your code on JSFiddle?

**Comment by straussCS** [comment]
@dennybiasiolli 
I just quickly took the plunker from https://github.com/sayanee/angularjs-pdf/issues/169.
See: https://plnkr.co/edit/Qg4pnwrBwK48nkom7OD4?p=preview

That's the Error I am experiencing. Am I misssing something here?

**Comment by dennybiasiolli** [comment]
Please try starting with our `example` folder files, in plunker from #169 and also in your plunkr needs to be added `pdf.worker.js`.
Another error is in `script.js`:
`$scope.templateUrl = '/test';`
Please provide an example starting from a working folder, like our `example` folder.

**Comment by DanLatimer** [comment]
Did anyone find a solution to this issue?

**Comment by nagano** [comment]
If anyone is still interested in this, you have to force a compilation using `$compile` or compile function in your directive, in order to turn `template-url` dynamic.

In my case it was being called inside another directive.
```
return {
    restrict: 'E',
    ,link: function(scope, element){
        const template = '<ng-pdf template-url="' + URL + '" canvasid="pdf"></ng-pdf>';
            element.append($compile(template)(scope));
    }
}
```
