### ISSUE TITLE
My PDF don't work

### ISSUE THREAD

**Issue by laurindo** [sayanee/angularjs-pdf#143]
I'm trying to load pdf from url firebase, but don't work because this error:

![screenshot 2016-09-30 00 50 17](https://cloud.githubusercontent.com/assets/2501144/18980204/5120aefa-86a8-11e6-9a5d-13a3f97bed01.png)

**Comment by simobasso** [comment]
@laurindo your problem is CORS https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS. You must config `Access-Control-Allow-Origin` header on your server side (firebase https://www.firebase.com/docs/hosting/guide/full-config.html#section-advanced-properties).
