### ISSUE TITLE
put a download button on the top nav

### ISSUE THREAD

**Issue by jpca999** [sayanee/angularjs-pdf#144]
how easy is it to put a download button on the top nav bar so that user can download the pdf to their device using angularjs-pdf ?

**Comment by RODOBTA** [comment]
You can do it directly on the server code, at least I did it that way, from the client I access through a button that links to a web API that is responsible for making the download process.

**Comment by dennybiasiolli** [comment]
@jpca999: as @RODOBTA says, you can do it directly on the server code
