### ISSUE TITLE
How to display entire pdf pages without any navigation menu

### ISSUE THREAD

**Issue by hardikpanseriya** [sayanee/angularjs-pdf#149]
I want to display entire pdf without any navigation menu in the browser.
How can I display all pdf pages with the scrollbar in the browser?
Thanks.

**Comment by dennybiasiolli** [comment]
Hi @hardikpanseriya , thanks for opening this issue.
I think this is a cool suggestion, but by now this feature is not planned in short term.
If you like you can make a pull request, we will appreciate your help.
Thanks 😄

**Comment by hardikpanseriya** [comment]
Can you please suggest me which angular plugin is better for entire PDF viewer?
Thanks.

**Comment by dennybiasiolli** [comment]
@hardikpanseriya you can try with angular-pdf-viewer or ng-pdfviewer.
https://github.com/sayanee/angularjs-pdf#similar-projects
