### ISSUE TITLE
Broken Tags In Example Partial?

### ISSUE THREAD

**Issue by johnjspiteri** [sayanee/angularjs-pdf#150]
The span tags are broken from line [2 to 9 in the example partial](https://github.com/sayanee/angularjs-pdf/blob/master/example/partials/viewer.html)...

`<button ng-click="goPrevious()"><span>&lt;</span></button>`

**Comment by dennybiasiolli** [comment]
Thanks @johnjspiteri 😄  I'm fixing the issue

**Comment by johnjspiteri** [comment]
Super Denny… Thank you for the amazing work here.
