### ISSUE TITLE
Why does Google reference this repo with [UNMAINTAINED]?

### ISSUE THREAD

**Issue by johnjspiteri** [sayanee/angularjs-pdf#154]
Why does Google reference this repo with [UNMAINTAINED]?

![screen shot 2016-12-07 at 11 22 31 pm](https://cloud.githubusercontent.com/assets/6007361/20997500/2243bcbe-bcd4-11e6-8b0c-7593c5c0994f.png)

**Comment by dennybiasiolli** [comment]
He is back MAINTAINED only a few weeks ago ;)
