### ISSUE TITLE
relativity name

### ISSUE THREAD

**Issue by kountouretis** [sayanee/angularjs-pdf#155]
When i try to load pdf with different name than relativity.pdf is not work.
For example if i change the   $scope.pdfUrl = 'pdf/relativity1.pdf'; is not work

**Comment by dennybiasiolli** [comment]
Do you have an example of your code?
`relativity1.pdf` is in the same path as `relativity.pdf`?

**Comment by kountouretis** [comment]
yes is the same path i put it in the pdf folder. My code is the same with the example

**Comment by dennybiasiolli** [comment]
`Error: Invalid page request`
Are you trying to get a page that doesn't exists on PDF? In our example default loaded page is `13`

**Comment by kountouretis** [comment]
Yes this is the problem.I changed the page and is work. Thank you.

**Comment by dennybiasiolli** [comment]
Thanks to you for the feedbak, have a nice day
