### ISSUE TITLE
Worker was destroyed

### ISSUE THREAD

**Issue by infotokabil** [sayanee/angularjs-pdf#156]
I am getting the below error while I am integrate the angularjs-pdf code into my application

Error: Worker was destroyed
Stack trace:
PDFWorker_setupFakeWorker/<@http://localhost:8080/rater-designer/scripts/lib/pdf.js:9759:40

Please give some solution..

**Comment by dennybiasiolli** [comment]
Are you trying to have multiple PDF.js viewer in one single page? Can you provide an example?

**Comment by infotokabil** [comment]
No I am having one PDF.js file only. The same code worked alone but while integrate it with my application it Shows that error..

Here I have include my pdf load code

			<div class="panel-body" id="temp-pdf-show">
				<div class="wrapper main-pdf-page" >
					<ng-pdf id="temp-pdf-div" template-url="views/pages/imageViewer.html" canvasid="pdf"
						page={{pageNum}}></ng-pdf>
				</div>
			</div>

**Comment by dennybiasiolli** [comment]
It seems a problem with some other part of your application, please provide a full example of the error on jsfiddle or another similar website. Thanks

**Comment by infotokabil** [comment]
It was big application have more angularJS routing and configuration. So I am unable to produce the same scenario in JSFiddle...

Can you please share in Which scenario the below will occur
      Error: Worker was destroyed
      Stack trace: PDFWorker_setupFakeWorker

And also please send If there is any possibility to destroy the already available worker while loading the page?

**Comment by dennybiasiolli** [comment]
Looking at [this page](https://github.com/mozilla/pdf.js/issues/7679), are you trying to load on the same page more than one pdf file (not PDF.js, but pdf documents)?
I don't need the full application, but only the bugged scenario, unless I can't reproduce the issue.

**Comment by dennybiasiolli** [comment]
@infotokabil do you have any news?

**Comment by simobasso** [comment]
closed for lack of response. @infotokabil feel free to reopen this issue
