### ISSUE TITLE
Creating Responsive Styles For Example Partial?

### ISSUE THREAD

**Issue by johnjspiteri** [sayanee/angularjs-pdf#162]
@dennybiasiolli, I am about to responsively style the [navigation buttons](https://github.com/sayanee/angularjs-pdf/blob/master/example/partials/viewer.html)  for a project tomorrow... would you like me to show you my work and possibly upgrade the example?

![screen shot 2016-12-28 at 4 59 36 pm](https://cloud.githubusercontent.com/assets/6007361/21532533/10f3f856-cd1f-11e6-8311-955e78128210.png)

**Comment by simobasso** [comment]
HI @johnjspiteri! thank you for your time and sorry for the late answer.

Pull requests are always welcomed on this repo, so feel free to open one any time you want!

Thanks

**Comment by simobasso** [comment]
closed for lack of response, @johnjspiteri feel free to reopen this one.
