### ISSUE TITLE
Bower not found

### ISSUE THREAD

**Issue by cristianurbano** [sayanee/angularjs-pdf#164]
Hi!

In the **1.4.0 version**, the **postinstall** script throw the folowing error:

`sh: 1: bower: not found`
`Failed at the angular-pdf@1.4.0 postinstall script 'bower install'.`

**Comment by simobasso** [comment]
Hi @cristianurbano!
Thanks for the report!

how you came to have this error?
it's the same on the last version (1.4.1)?

**Comment by cristianurbano** [comment]
Hi @simobasso , [in the npm](https://www.npmjs.com/package/angular-pdf), we don't have the 1.4.1 version

**Comment by dennybiasiolli** [comment]
Sorry @cristianurbano , my mistake. I've updated to 1.4.1 in npm now, this will fix the issue.
Let us know if it's correct :)

**Comment by cristianurbano** [comment]
Thanks @dennybiasiolli , now the version 1.4.1 is in npm, but the error still there

![error-angular-pdf](https://cloud.githubusercontent.com/assets/2442937/21643250/131eb82c-d266-11e6-8731-83f99eece821.png)

**Comment by dennybiasiolli** [comment]
Hi @cristianurbano , thanks to your report I fixed the issue.
Now on NPM there is the new version of angular-pdf: 1.5.0.
Thanks a lot. :tada:

**Comment by cristianurbano** [comment]
Thanks @dennybiasiolli now it works as expected
