### ISSUE TITLE
angular-pdf.js directive remove "read-only"

### ISSUE THREAD

**Issue by joserojasv** [sayanee/angularjs-pdf#166]
Hello
I was hoping may be you can give me a hand...

My issue is that looks like the directive canvas (viewer) is "read-only" I'm trying to mark some text to copy but is not possible, it looks like there is a top layer blocking, or like if the pdf is an image or svg, I was thinking if there is a way I can change this page mode?

and my second issue is I have some links inside the pdf pages, that render to another page, but we are not able to click them... we found some info about enable externalLinkTarget property but didn't work I think because the read-only mode but is just hunch we are not sure...

We'll appreciate any  info you could give us please...

thanks you.

Jose Rojas

**Comment by dennybiasiolli** [comment]
Hi @joserojasv , now this directive doesn't render the TextLayer or links but only the page.
This is a useful feature, any help will be welcome! 😄
