### ISSUE TITLE
Full sample of how to load a PDF from a base64 string?

### ISSUE THREAD

**Issue by mayacr86** [sayanee/angularjs-pdf#167]
Hi @sayanee , let me thank you first for the awesome library!

Just wondering, do you have a complete - dummy like - sample to load a PDF from a base64 string?

Let's say I have something like:

const pdfAsBase64 = "data:application/pdf;base64,JVBEfghfgh..."; // shortened

**Comment by sayanee** [comment]
@dennybiasiolli will be able to help more as he's the current maintainer 👏

**Comment by dennybiasiolli** [comment]
Hi @mayacr86 , looking at [this example](https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html) you can render a pdf from a base64 string using `PDFJS.getDocument({data: pdfDataEncoded})`.
Now in the directive we accept only the PDF's url, but this feature will be considered in future releases, so the user can pass a base64 string instead of the url.
Thanks for the suggestion! 😃

**Comment by dennybiasiolli** [comment]
Sorry @mayacr86, I gave you an incorrect answer.
We have a full working example at [this url](https://github.com/sayanee/angularjs-pdf/issues/110#issuecomment-269547160) thanks to @johnjspiteri.
You can use in this way:
```
currentBlob = new Blob([result], {type: 'application/pdf'});
$scope.pdfUrl = URL.createObjectURL(currentBlob);
```

**Comment by v1r0x** [comment]
I hope it is ok to describe my problem with the provided method here.
I also get the pdf content as base64 and want to display it. Unfortunately our server is behind a proxy and the `URL.createObjectURL` returns an URL using the root of the webserver.

Example:
Our server: `https://subdomain.domain.tld/company/project1/...`
URL returned by `URL.createObjectURL`: `https://subdomain.domain.tld/<object-URL>`
I hope you understand my confusing explanation :sweat_smile: 

Is there any other chance to load a base64-encoded pdf?

**Comment by ansarikhurshid786** [comment]
Than you @dennybiasiolli, for giving correct solution. can you please share how to display it.
