### ISSUE TITLE
need Help with Installation

### ISSUE THREAD

**Issue by Weestdudochnicht** [sayanee/angularjs-pdf#169]
I build i Plunker with your Directive https://plnkr.co/edit/rtdklaz4nNbuRzbcWcAf?p=preview

I try to use angular-pdf with Base64 url.

My Problem is NOT the usage of base64. The Problem is the Directive.

Could u Please help me fixing the Plunker so that i be able to use the Directive?

Btw.  my plunker is based on your demo but with a base64 testpdf.

**Comment by simobasso** [comment]
Hi @Weestdudochnicht ! Thank you for the issue.

I think your plunker it's not complete.

for example: where is the template's file?
You can continue here https://plnkr.co/edit/G6s1jQ0ObbJxD2cVx8jF?p=preview

**Comment by Weestdudochnicht** [comment]
thanks for your fast answer. but your plunker also show no pdf.

So what is the problem in there?
thanks for every help

**Comment by dennybiasiolli** [comment]
Hi @Weestdudochnicht ,
looking at your plunkr, you need to include also `pdf.worker.js` to have a full working example.
😉

**Comment by Weestdudochnicht** [comment]
thanks now the plunker works.

**Comment by Weestdudochnicht** [comment]
i found something strage. plunker: https://plnkr.co/edit/rtdklaz4nNbuRzbcWcAf?p=preview

i used that link  <script src="https://sayan.ee/angularjs-pdf/js/lib/pdf.worker.js"></script> to import the pdf.worker.js and i also create a empty pdf.worker.js in the plunker. if i remove the empty file the plunker wouldnt work! I dont know why but it happen.

Anyways it works in the plunker.
Now for My application it will not run. 
I Import the following:
     'src/app/plugins/pdfjs-dist/web/compatibility.js',
     'src/app/plugins/pdfjs-dist/build/pdf.js',
     'src/app/plugins/pdfjs-dist/build/pdf.worker.js',
     'src/app/plugins/angularjs-pdf/dist/angular-pdf.js',
im using  "angular": "~1.5.9".
i use the following code in my documentUpload.html 

  <div class="wrapper col-md-12" >
            <h1>test it</h1>
            <ng-pdf template-url="partials/viewer.html" canvasid="pdf" scale="page-fit"></ng-pdf>
        </div>


        <script type="text/ng-template" id="partials/viewer.html">
            <nav ng-class="getNavStyle(scroll)">
                <button ng-click="goPrevious()"><span>&lt;</span></button>
                <button ng-click="goNext()"><span>&gt;</span></button>

                <button ng-click="zoomIn()"><span>+</span></button>
                <button ng-click="fit()"><span>100%</span></button>
                <button ng-click="zoomOut()"><span>-</span></button>

                <button ng-click="rotate()"><span>90</span></button>

                <span>Page: </span>
                <input type="text" min=1 ng-model="pageNum">
                <span> / {{pageCount}}</span>

                &nbsp;&nbsp;
                <span>Document URL: </span>
                <input type="text" ng-model="pdfUrl">
            </nav>

            <hr>

            {{loading}}
            <canvas id="pdf" class="rotate0"></canvas>
        </script>

in the controller i used the same code as in the plunker to load the pdf. i bind the html via templateUrl: 'directives/documentUpload/documentUpload.html' in the controller.

My result i see nothing except the header  <h1>test it</h1>

u got any hints for me?

**Comment by dennybiasiolli** [comment]
@Weestdudochnicht can you please report here the errors in your browser's console?

**Comment by Weestdudochnicht** [comment]
there are no errors. thats my problem. I believe its about the Integration of
 <script type="text/ng-template" id="partials/viewer.html">

bec. i dont even see the button nav.

**Comment by dennybiasiolli** [comment]
Can you provide an example of this latest code?

**Comment by Weestdudochnicht** [comment]
I updated the plunker now: https://plnkr.co/edit/rtdklaz4nNbuRzbcWcAf?p=preview

**Comment by Weestdudochnicht** [comment]
now i noticed that makes no sence to use my code in a plunker -_-

**Comment by dennybiasiolli** [comment]
In the browser's console I see this error: `Error: [$controller:ctrlreg] The controller with the name 'DocCtrl' is not registered.`.
Take a look at your angular code. 😉 

Another hint: you need to use the same version of `pdfjs.js` and `pdfjs.worker.js` to avoid further errors.

**Comment by Weestdudochnicht** [comment]
So. Now i got a better version of the plunker: https://plnkr.co/edit/rtdklaz4nNbuRzbcWcAf?p=preview

Thas the small view of my code. In the Plunker the Nav works in my app not. In Both the angular-pdf directive doesnt work

**Comment by dennybiasiolli** [comment]
Like I said in the previous comment:

> you need to use the same version of `pdf.js` and `pdf.worker.js`

```
    <script src="https://sayan.ee/angularjs-pdf/js/lib/pdf.js"></script>
    <script src="https://sayan.ee/angularjs-pdf/js/lib/pdf.worker.js"></script>
```

I suggest you to use a local pdfjs libs instead of the online one.

**Comment by Weestdudochnicht** [comment]
yeah i do so in my appliaction but i cant use my local plugins in the plunker

**Comment by Weestdudochnicht** [comment]
IT worked in the Plunker. So it have to work in my application. I hva to check the plugin installation. sry that i waste your time. You can close that issue

**Comment by dennybiasiolli** [comment]
Thanks for your feedback, glad you solved. 🎉
