### ISSUE TITLE
 I met this problem, I do not know how to solve, I need your help，thanks

### ISSUE THREAD

**Issue by LYXmoonstars** [sayanee/angularjs-pdf#171]
XMLHttpRequest cannot load http://10.1.1.19/attachments/571f68bd87c4.pdf. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

**Comment by dennybiasiolli** [comment]
Hi @LYXmoonstars, this isn't a problem with the frontend, you have to correctly set 'Access-Control-Allow-Origin' on your server.
Hope [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) helps.
😃
