### ISSUE TITLE
Option to scroll in place of changing page 

### ISSUE THREAD

**Issue by popod** [sayanee/angularjs-pdf#172]
Is there an option to scroll in place of going to page 2 ?
Thanks

**Comment by dennybiasiolli** [comment]
Hi @popod , thanks for the issue.
Where do you intend to scroll? In the [example page](http://www.lercio.it/qual-e-un-tuo-proposito-per-il-2017/) you can scroll in the page.

**Comment by dennybiasiolli** [comment]
Hi @popod , thanks for the issue.
Where do you intend to scroll? In the [example page](https://sayan.ee/angularjs-pdf/) you can scroll in the page.

**Comment by popod** [comment]
Hi, thanks for answer !
I want to scroll across pages without need to switch page number with the buttons.

**Comment by dennybiasiolli** [comment]
Thanks for clarification, this is not possible with this directive. You have to implement it in other way. 😃
