### ISSUE TITLE
Error: PDFJS is not defined

### ISSUE THREAD

**Issue by mrjainvimal** [sayanee/angularjs-pdf#175]
Error: PDFJS is not defined
.link@http://localhost:3000/bower_components/angular-pdf/dist/angular-pdf.js:59:9
bind/<@http://localhost:3000/bower_components/angular/angular.js:1291:15
invokeLinkFn@http://localhost:3000/bower_components/angular/angular.js:10249:9
nodeLinkFn@http://localhost:3000/bower_components/angular/angular.js:9638:11
compileTemplateUrl/<@http://localhost:3000/bower_components/angular/angular.js:9977:13
processQueue@http://localhost:3000/bower_components/angular/angular.js:16643:37
scheduleProcessQueue/<@http://localhost:3000/bower_components/angular/angular.js:16683:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:3000/bower_components/angular/angular.js:17958:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:3000/bower_components/angular/angular.js:17772:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:3000/bower_components/angular/angular.js:18066:13
done@http://localhost:3000/bower_components/angular/angular.js:12207:36
completeRequest@http://localhost:3000/bower_components/angular/angular.js:12433:7
requestLoaded@http://localhost:3000/bower_components/angular/angular.js:12361:9
 <ng-pdf style="display: block;" template-url="/views/viewer.html"> angular.js:14324:18

**Comment by dennybiasiolli** [comment]
Hi @mrjainvimal,
have you included PDFJS in your sources?

**Comment by mrjainvimal** [comment]
forgot to include, now included but got unexpected error

**Comment by dennybiasiolli** [comment]
Please refer to section `5` of `Getting started` in Readme file.
https://github.com/sayanee/angularjs-pdf/blob/master/readme.md#getting-started
