### ISSUE TITLE
Error: canvas is null

### ISSUE THREAD

**Issue by mrjainvimal** [sayanee/angularjs-pdf#176]
Error: canvas is null
.link@http://192.168.1.143:3001/bower_components/angular-pdf/dist/angular-pdf.js:50:13
bb/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:16:54
ja@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:81:35
m@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:66:274
$/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:76:459
e/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:130:409
vf/this.$get</m.prototype.$eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:145:103
vf/this.$get</m.prototype.$digest@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:142:165
vf/this.$get</m.prototype.$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:145:399
l@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:97:248
K@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:101:373
gg/</y.onload@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:102:397
 <ng-pdf style="display: block;" template-url="/viewer.html">

**Comment by dennybiasiolli** [comment]
Please refer to section `5` of `Getting started` in Readme file.
https://github.com/sayanee/angularjs-pdf/blob/master/readme.md#getting-started
