### ISSUE TITLE
IE 11 incompatible

### ISSUE THREAD

**Issue by nemoinho** [sayanee/angularjs-pdf#177]
angular-pdf blocks IE 11 compatibility of angular-js due to it's dependency on angular 1.6.0 because of a bug which is fixed in angular 1.6.2

Please update dependency to ~1.6 or 1.6.2

[fix(angularInit): allow auto-bootstraping from inline script](https://github.com/angular/angular.js/pull/15571)

**Comment by dennybiasiolli** [comment]
Hi @nemoinho, thanks for this issue.
We will provide this update as soon as possible, thanks for the suggestion

**Comment by dennybiasiolli** [comment]
@nemoinho 1.5.1 released with the fix 😉
