### ISSUE TITLE
Words of pdf are srambled

### ISSUE THREAD

**Issue by ammar08429** [sayanee/angularjs-pdf#178]
when i try this PDF in pdf.js it works fine, but when i try it in angularjs-pdf, this is how i see the pdf

<img width="510" alt="screen shot 2017-02-20 at 6 51 48 pm" src="https://cloud.githubusercontent.com/assets/6717231/23132193/e6c3ed62-f79d-11e6-89bb-e2129d9f77be.png">

is there anything i am missing?

**Comment by dennybiasiolli** [comment]
Hi @ammar08429, thanks the issue, can you provide an example with your code and the PDF?

**Comment by ammar08429** [comment]
`<ng-pdf template-url="/www/app/components/pdf/viewer.html" debug="true"></ng-pdf>`
i generated the pdf.js and worker file, added ngPdf directive in to my own angular module
and i tried multiple files , here are two below
[sample.pdf](https://github.com/sayanee/angularjs-pdf/files/787983/lala.pdf)
[arabic-book.pdf](https://github.com/sayanee/angularjs-pdf/files/787974/grade12.pdf)

**Comment by dennybiasiolli** [comment]
Thanks @ammar08429,
on my MacOS 10.12.3, with Chrome v56, I see your two pdfs in the correct way.

Have you tried to clone this repo and put your pdf in the `example` folder? Then you can launch our example site with `npm start` and open your pdf writing its url in the textbox (`pdf/lala.pdf`).

In my case all works correctly.

If your error persists you can write a simple example on [JSFiddle](https://jsfiddle.net/).

Thanks!

**Comment by ammar08429** [comment]
Thanks @dennybiasiolli 
Found the problem
the parent div in which i added the directive had this css 
`direction: rtl;`
which was causing this problem

**Comment by dennybiasiolli** [comment]
Thank you @ammar08429 for the feedback
