### ISSUE TITLE
stream must have data on second load of PDF

### ISSUE THREAD

**Issue by TrueGeek** [sayanee/angularjs-pdf#181]
I'm using angularjs-pdf in an Ionic mobile app. It works wonderfully (thank you!) the first time I load a PDF. However, the second time the onError event fires with the message:

> stream must have data

I get this even when reloading the save PDF twice in a row. Has anyone else seen this?

**Comment by dennybiasiolli** [comment]
Hi @TrueGeek, thanks for opening this issue :)
Can you please provide a working example app so we can analyse the issue?
Thanks!

**Comment by TrueGeek** [comment]
It turns out this issue was caused by the PDF not being written in time before the viewer started up. I'm not sure why it always worked the first time and not the second but I solved it by switching to a file writer that returned a promise so I could wait for the PDF to be written to disk before setting pdfURL to scope.

Thanks!

**Comment by dennybiasiolli** [comment]
Thanks for the feedback @TrueGeek ! :)
