### ISSUE TITLE
Selectable text

### ISSUE THREAD

**Issue by rorydpayne** [sayanee/angularjs-pdf#183]
I know this issue has been opened and closed a couple of times, but I was trying to get text selection working yesterday. It was reasonably straight forward using getTextContent and by including the web/pdf_viewer.js and web/pdf_viewer.css from pdfjs.  
  
Happy to tidy this up a bit and raise a PR if there's interest.

**Comment by dennybiasiolli** [comment]
Hi @rorydpayne, thanks for this issue, we are finishing the tests for PR #163 to modularize this directive.
I know that including `web/pdf_viewer.js` and `web/pdf_viewer.css` it's possible to use PDFJS's extended features to show selectable text, we can implement this feature after PR is merged.
We are glad to accept your help, what do you think about PR #163 ?

**Comment by rorydpayne** [comment]
Hi @dennybiasiolli . That's fine - I think the changes in #163 are a good move. I am happy to rework the selectable text functionality after #163 has been merged

**Comment by dennybiasiolli** [comment]
Thanks @rorydpayne, we are plannig a release within the beginning of the next week, stay tuned! ;)

**Comment by rhyskoedijk** [comment]
@rorydpayne I also started looking in to selectable text (and search/find) myself, great to see others are working towards this as well. Very keen to see #163 merged and the community functionality/PRs that follow it.

**Comment by simobasso** [comment]
@rorydpayne @rhyskoedijk #184 is merged! feel free to submit your PRs

**Comment by NBE1** [comment]
@rorydpayne Any updates on your progress?
