### ISSUE TITLE
Need help , My question , I can't show chinese in my project 

### ISSUE THREAD

**Issue by dinglittle** [sayanee/angularjs-pdf#188]
In my project ,I use the angular-pdf , but  , it's  can't show  chinese pdf , help me ,thanks !!!

**Comment by dennybiasiolli** [comment]
Hi @dinglittle , can you provide an example of your code and PDF? Thanks

**Comment by dinglittle** [comment]
Thanks you reply !

Now I have another question  , as this , I set $scope.pdfUrl to 
`"http://xxxx.x.xx.x:8880/utf8-jsp/ueditor/jsp/upload/file/20170522/1495422075553029472.pdf"
`
(my fileserver address) , but can't show the pdf , like demo , the error 
```XMLHttpRequest cannot load http://xxxx.x.xx.x:8880/utf8-jsp/ueditor/jsp/upload/file/20170522/1495422075553029472.pdf. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.```
is that , I can not  show the pdf , not in my Local Directory ?

And I use the Demo `https://sayan.ee/angularjs-pdf/` change de Document URL as a  internet addres , the error 

```Mixed Content: The page at 'https://sayan.ee/angularjs-pdf/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://120.26.131.205:8190/utf8-jsp/ueditor/jsp/upload/file/20170523/1495529485377072631.pdf'. This request has been blocked; the content must be served over HTTPS.```

So what is reason , I can't show my pdf ?

Hope your reply!!!

**Comment by dennybiasiolli** [comment]
Hi @dinglittle , your second issue can be solved with a simple search in [our issue](https://github.com/sayanee/angularjs-pdf/search?q=Access-Control-Allow-Origin&type=Issues&utf8=%E2%9C%93)
It's not a problem with this directive but is a server problem. ;)
