### ISSUE TITLE
What caused the release of the major-version 2.0.0?

### ISSUE THREAD

**Issue by NicoBurno** [sayanee/angularjs-pdf#198]
I ask because I don't understand why it was necessary to release the major-version. Backwards compatibility is supported in full measure...
Usually in such cases, a minor version release. For example, 1.7.0

@dennybiasiolli can you help with this question?

**Comment by dennybiasiolli** [comment]
@NicoBurno release of major version 2.0.0 is caused by commit ea8056c, discovered by #197.
Two weeks ago we merged a PR with the creation of a dynamic canvas, but I forgot to release the major version.

**Comment by NicoBurno** [comment]
@dennybiasiolli I understood. Thank you.
