### ISSUE TITLE
Links within pdfs not working?

### ISSUE THREAD

**Issue by mobpakrd** [sayanee/angularjs-pdf#200]
Hello, 
We have implemented angularjs-pdf and things are generally working well except that links in pdfs are not clickable. They just render without being links. I've attached a pdf with links that works fine in pdf-js but in our app does not work. We are currently using version 1.5.5 of angularjs-pdf. https://mozilla.github.io/pdf.js/web/viewer.html
Additionally the demo at https://sayan.ee/angularjs-pdf/ appears to have links in it, for instance footnotes, and a mailto that are simply appear blue without being clickable.
Is this a known issue with angularjs-pdf or do links work for others and perhaps something about our implementation is screwing it up? 
Below is where things are included, I can provide further details if needed.

```
            <ng-pdf
                    template-url="components/file_view/pdf_viewer.tpl.html"
                    canvasid="pdf"
                    scale="page-fit">
            </ng-pdf>
```
pdf_viewer.html:
```
{{loading}}
<canvas id="pdf" class="rotate0"></canvas>
```

[sample_pdf.pdf](https://github.com/sayanee/angularjs-pdf/files/1128769/sample_pdf.pdf)

**Comment by dennybiasiolli** [comment]
Hi @mobpakrd,
unfortunately this directive display pdfs without the text layer, so links are not clickable.
If you have some spare time, any helps and PR will be appreciated  😄

**Comment by mobpakrd** [comment]
@dennybiasiolli if I were to go about making that change, how would you recommend going about it? Are there perhaps other libraries that do handle the text layer that I could look at? I'm not super familiar with pdfs but this is an important thing for us so if it's not overwhelming you might be a looking at a pr not too far away.

**Comment by dennybiasiolli** [comment]
@mobpakrd a good starting point is in pdf.js code, something like the link you posted: https://mozilla.github.io/pdf.js/web/viewer.html
😉
