### ISSUE TITLE
pageCount is not getting refresh when i open second pdf.

### ISSUE THREAD

**Issue by tarunmeena512** [sayanee/angularjs-pdf#204]
hi
pageCount is not getting refresh when i open the second pdf unless and until second pdf data is not loaded successfully .

**Comment by tarunmeena512** [comment]
![1 pdf](https://user-images.githubusercontent.com/30525908/28715413-7d114614-73b5-11e7-8666-c2ff87b4134c.png)
![2 pdf](https://user-images.githubusercontent.com/30525908/28715418-81cbbec8-73b5-11e7-857f-070b3991ca44.png)

**Comment by tarunmeena512** [comment]
pageCount refresh only after second pdf data loaded successfully.

**Comment by dennybiasiolli** [comment]
Hi @tarunmeena512, can you provide an example on jsfiddle or something similar? Thanks! 😉

**Comment by tarunmeena512** [comment]
hi, @dennybiasiolli could you please check the screenshots that I mentioned above ...like here the issue is pdf is showing loading but page count is 1/3 (which is the previous pdf page count) and i want if every time we open new pdf it should be like 1/0.  
how can i  set **pageCount = 0**; every time when i open new pdf.

**Comment by dennybiasiolli** [comment]
Hi @tarunmeena512, can you please provide an example on jsfiddle or something similar? So I can look at the code. Thanks! 😉
