### ISSUE TITLE
pdf viewer is not loading pdf file in case of all librbaries bundles into one lib.js

### ISSUE THREAD

**Issue by kalebakula** [sayanee/angularjs-pdf#205]
Hi
In our aplication all the library files gets bundled into one lilb,js where pdf.js and pdf.worker.js also part of bundle

whenever we give valid url to $scope.pdfUrl, it looks for lib.worker.js because of this line  return pdfjsFilePath.replace(/\.js$/i, '.worker.js'); 
getting 404 not found since it is not present
If i comment this line and return pdfjsFilePath alone it works

Is this the only way to handle or any other configuration available

**Comment by dennybiasiolli** [comment]
Hi @kalebakula, I think you should put `pdf.worker.js`, take a look at this example of pdf.js: https://github.com/mozilla/pdf.js/tree/master/examples/webpack
