### ISSUE TITLE
control toolbar on directive

### ISSUE THREAD

**Issue by faizalpribadi** [sayanee/angularjs-pdf#210]
Why not showing print or download button on toolbar like previous and next button ? can you explain about that ? in there, pdfjs allowed download and print by default, thanks 

ping @sayanee  @dennybiasiolli

**Comment by dennybiasiolli** [comment]
Hi @faizalpribadi,
this is a simple
> AngularJS directive to display PDF files with PDFJS.
What you see in demo page is only an example, but feel free to submit a PR if you want. 😉

**Comment by faizalpribadi** [comment]
@dennybiasiolli , can you explain about what you say **this is simple** ? , i read this issue from this https://github.com/sayanee/angularjs-pdf/issues/111 , until now, feature does not implemented

**Comment by dennybiasiolli** [comment]
@faizalpribadi , i wrote that *"this is **a** simple AngularJS directive to display PDF files with PDFJS"*.

As you can read in #111 
> Currently we don't have this feature. Happy to look at a pull request on this! Feel free to re-open this issue with a pull request.

So we are happy to look at a PR on this feature, but currently we don't have this feature 😉
