### ISSUE TITLE
show all individual pages just beside viewer  in tiny size 

### ISSUE THREAD

**Issue by kalebakula** [sayanee/angularjs-pdf#212]
show all individual pages just beside viewer  in tiny size  so that user can directly select the page and view that page in viewer and do other operations like delete

**Comment by dennybiasiolli** [comment]
Hi @kalebakula,
this is a simple
> AngularJS directive to display PDF files with PDFJS.

You can implement your own viewer using a directive for each page you need to show, but this directive works showing only a single page.
