### ISSUE TITLE
how to use dynamic template-url

### ISSUE THREAD

**Issue by SwanHtetKyaw24** [sayanee/angularjs-pdf#225]
Can template-url value can be dynamically assigned from controller or dom?
I would like to use like this 

> <ng-pdf template-url=`{{pdfTemplateUrl}}` id="pdfpreview"></ng-pdf>

Currently whatever value use for template-url is only regarded as string value. Is there a work around to avoid this manner? I also found out that issue #142  is same as this but there is no visible and working answer provided in that issue.

**Comment by dennybiasiolli** [comment]
Hi @SwanHtetKyaw24 

I think the only solution is to force a compilation using `$compile`, like in the example at [this comment](https://github.com/sayanee/angularjs-pdf/issues/142#issuecomment-398169228)

**Comment by SwanHtetKyaw24** [comment]
Thz for reply. I use a work-around by directly using pdf.js and angular-pdf.min.js. In that way, that issue can be avoided though I had to manually create canvas to handle showing PDF.
