### ISSUE TITLE
Progress Bar or Loading

### ISSUE THREAD

**Issue by AbhayNawathey** [sayanee/angularjs-pdf#28]
How can we show the progress or loading spinner while the PDF is loading from the server. It takes a while before it actually displays the PDF so just a curious question if can show some spinner may be with pages loading

**Comment by sayanee** [comment]
:+1: totally agree!

**Comment by jlebensold** [comment]
bump!

**Comment by sayanee** [comment]
closed with b2d291182f9adec5e839d78e7d937e63c818f84c and 4b5dc9832cd052cbcc9dcc7035bab8d07951c79b

**Comment by sayanee** [comment]
thanks for the suggestions again :smiley:  2 events are now exposed: 

1. `onLoad` will be executed when the pdf is fully loaded ([check docs](https://github.com/sayanee/angularjs-pdf#show-loading))
- `onProgress` will be executed with progress loaded and total details ([check docs](https://github.com/sayanee/angularjs-pdf#show-progress-percentage) and [example's browser console](http://sayan.ee/angularjs-pdf/))
