### ISSUE TITLE
pdf  worker

### ISSUE THREAD

**Issue by Wooleners** [sayanee/angularjs-pdf#29]
In the compression of time I found PDF always request worker JS but I am in your JS is set inside the worker disblead found no effect

**Comment by sayanee** [comment]
Yes [pdfjs](https://github.com/mozilla/pdf.js/), which is a dependancy will use `pdf.worker.js` as defined in the [example folder](https://github.com/sayanee/angularjs-pdf/tree/master/example). 

Let me know if there are other errors.
