### ISSUE TITLE
Handle PDFJ.getDocument error

### ISSUE THREAD

**Issue by picolo74** [sayanee/angularjs-pdf#31]
Hi,

I have a lot of pdf wich can not be opened by the lib and the directive does not handle errors.

you just have to handle the  PDFJS.getDocument() promise error.

and allow to bind a function to handle it outside the directive

Thank you

**Comment by sayanee** [comment]
thanks for the idea @picolo74! 

It is important to handle the error. Please [try this now](https://github.com/sayanee/angularjs-pdf#handle-error) as updated in the readme.

**Comment by picolo74** [comment]
Thank you, works great !
