### ISSUE TITLE
Is there a way to load all pages, so that the page can be scrolled like in pdf js viewer

### ISSUE THREAD

**Issue by madhu131313** [sayanee/angularjs-pdf#44]
I have issues using pdf js viewer,so I want this so that I can scroll through all pages.

**Comment by sayanee** [comment]
No, that is not supported as it will not be a simple viewer anymore.

Hope the dependancy module [pdf js](http://mozilla.github.io/pdf.js/#) itself will be useful for this purpose. Here's [an example](http://mozilla.github.io/pdf.js/web/viewer.html)

**Comment by madhu131313** [comment]
Thanks, I know i can use PDF JS viewer but pdfjs viewer is not good for
customization.

[image: photo]
*Madhu Sudhan*
Founder, CEO, Kroods Technologies
m:7418991535 | w:http://kroodstech.com
<https://www.facebook.com/KroodsTech>
<https://www.linkedin.com/profile/view?id=95937344>

**Comment by saawan787** [comment]
How to load entire pdf in the viewer??

**Comment by madhu131313** [comment]
Try this Bootstrap PDF JS Viewer

https://github.com/justindarc/bootstrap-pdf-viewer/ , Let me know if that
suffices your requirement

Thanks and Regards,


*Madhu Sudhan*
Co-Founder, PutPeace App
m:7418991535 | w:http://putpeace.com
<https://www.facebook.com/madhu.one.three>
<https://www.linkedin.com/profile/view?id=95937344>

**Comment by saawan787** [comment]
Hi,
Bootstrap PDF JS Viewer is nice.but how can perform some actions when reaching a specified page.i have generate a bootstrap modal when reaching a specified page.suppose given 4 as input then modal box generate on the pdf page number 4 using scrolling.If this possible using this Bootstrap PDF JS Viewer please asap me solution for that.
Thanks in advance!!

**Comment by stefan2904** [comment]
I was also a bit confused that this is not supported, since its a basic feature of PDFJS ...

**Comment by vikasyadav11** [comment]
Anyone has code on angular 2+ ? Please provide the link
