### ISSUE TITLE
how do you change the pdf source

### ISSUE THREAD

**Issue by terencemutizwa** [sayanee/angularjs-pdf#46]
When i change the pdf url in the controller, it dosn't render the new pdf

**Comment by sayanee** [comment]
Any code sample and error messages from the browser console?

**Comment by fernoftheandes** [comment]
@sayanee, this is related to issue #42. You do not have a watch for the changes to `pdfUrl`. Here is a snippet of code that can do it (inside `angular-pdf.js`):

    scope.$watch('pdfUrl', function(newVal) {
          if(newVal !== ""){
            console.log("pdfUrl value change detected: ", scope.pdfUrl);
            url = newVal;
            scope.pageToDisplay = 1;
            renderPDF();
          }
    });

But you should also wrap your `PDFJS.getDocument` function like this (inside `angular-pdf.js` as well):

    if(url && url.length){
            PDFJS.getDocument(url, null, null, scope.onProgress).then(
            ...

I can create a pull request if you would like, but these are the 2 changes needed to change PDFs dynamically. Or you may prefer to do it differently.

**Comment by sayanee** [comment]
thanks @fernoftheandes - yes please send a pull request

**Comment by benlooi** [comment]
hello! I had to solve this for my project. Managed to do exactly what @fernoftheandes suggested. It works!
So in my Controller, I can now assign values to $scope.pdfUrl and it updates my template. I am using a Semantic UI modal to show PDF files when clicked on a list of ng-repeat divs, so each ng-click calls a function that passes a value that forms part of the pdfUrl string.

**Comment by fernoftheandes** [comment]
Yes, the solution works well...let's hope @sayanee will accept the pull request. It's been sitting there for a few weeks now.

**Comment by sayanee** [comment]
#49

**Comment by sayanee** [comment]
Thanks you so much @fernoftheandes. We can all now download the latest version `1.0.2` with `bower i angular-pdf` :tada:
