### ISSUE TITLE
pdf viewer not working in safari

### ISSUE THREAD

**Issue by xudongli113** [sayanee/angularjs-pdf#47]
The demo seems not working in Safari browser, any idea how to solve this?

many thanks
xudong

**Comment by F3L1X79** [comment]
Same here. Would like to know if it would take much time to make a fix or not becauser the console is not displaying any errors.

Thanks a lot for the hard work btw.

**Comment by F3L1X79** [comment]
Nevermind, it seems to be working with the compatibility.js file of PDF.JS and your last commit.

**Comment by sayanee** [comment]
Yes, I also realised that with Safari, it was varying for the older version. It seems to be fixed now.
Feel free to open this when the problem re-occurs.

![image](https://cloud.githubusercontent.com/assets/413879/11061814/9b2ff80c-87e4-11e5-8b31-e1fdc9feaa76.png)
