### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Rajesh20243034** [sayanee/angularjs-pdf#50]
Invalid parameter in getDocument, need either Uint8Array, string or a parameter object

**Comment by sayanee** [comment]
Seems like an error from the underlying dependancy pdf.js:

https://github.com/mozilla/pdf.js/blob/d3e90cf825ae7af85f250db7d4b168d9cdce3214/src/display/api.js#L264-L265

You might wanna check this: http://stackoverflow.com/questions/30319343/which-java-datatype-is-required-when-calling-javascript-method
