### ISSUE TITLE
page-fit doesn't work

### ISSUE THREAD

**Issue by rwwagner90** [sayanee/angularjs-pdf#52]
I am trying to render a responsive pdf, and page-fit will not work. I noticed one problem. scale is set like so:

```js
scale = attrs.scale > 0 ? attrs.scale : 1,
```

Then the page-fit logic does this if:

```js
if (attrs.scale === 'page-fit' && !scale) {
```

That will never be true, because scale gets set to `1` by the ternary statement.

Even when I remove the second condition from the if, it still does not work though. clientWidth and clientHeight are both 0, so it doesn't scale anything.

Would be awesome to get this working, and I don't mind doing the work, if someone can give me a little guidance.

**Comment by rwwagner90** [comment]
@sayanee I got around this by just manually calculating the scale in my app and passing it to the directive. I may be able to adjust my logic a bit and fix page-fit.

**Comment by dohomi** [comment]
I have seen the same issue. What are the referenced forks? Are they planed to get merged into the current repo?
