### ISSUE TITLE
How to load entire pdf in the viewer?

### ISSUE THREAD

**Issue by saawan787** [sayanee/angularjs-pdf#55]

**Comment by sayanee** [comment]
related #45

**Comment by simobasso** [comment]
@sayanee what is your opinion on this request? it's ok for you? can I try to pull request?

**Comment by sayanee** [comment]
Sure @simobasso :smiley:

**Comment by sayanee** [comment]
For code reference to implement multi-page with PDFJS: https://github.com/izuzak/atom-pdf-view

**Comment by sayanee** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open it with a pull request on the feature 🤗
