### ISSUE TITLE
display the pdf if the url is base64 or Uint8Array

### ISSUE THREAD

**Issue by dohomi** [sayanee/angularjs-pdf#62]
Hi @sayanee the pdfjs-dist is currently in ```1.2.83```. Any plan of updating the bower to the newest version or any known bugs?
https://github.com/mozilla/pdfjs-dist/blob/master/package.json

**Comment by sayanee** [comment]
Yes, I will upgrade it to `1.2.83`. 

Does this version display the pdf if the `url` is [base64 or Uint8Array](https://github.com/sayanee/angularjs-pdf/commit/641b5753bc2cb3249751401f851da40497a1a26e#commitcomment-14260730)? Help me test it with your use case. Thank you!

**Comment by dohomi** [comment]
What I basically did solving it I created a Blob
```
currentBlob = new Blob([result], {type: 'application/pdf'});
$scope.pdfUrl = URL.createObjectURL(currentBlob);
```
Now it works. Importantly ```pdfUrl```now needs to be a string of existing ```http```string, otherwise it won't work. Before the change it could be the raw ```Uint8Array```but I can live with the change. Thanks for your update and feedback.
