### ISSUE TITLE
Pdf url set as an attribute instead of use $scope

### ISSUE THREAD

**Issue by jcampalo** [sayanee/angularjs-pdf#71]
Maybe is not an issue, but it will be a major improvement setting pdfUrl
 throught an attribute of the directive instead of using controller's scope.

**Comment by simobasso** [comment]
Hi @jcampalo thanks for the proposal.

What do you think to submit a pull request?

**Comment by sayanee** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open it with a pull request on the feature 🤗
