### ISSUE TITLE
blank canvas when $route.reload() if ngAnimate is in module dependances

### ISSUE THREAD

**Issue by soubok** [sayanee/angularjs-pdf#72]
Hello,
the testcase is here: http://jsbin.com/fuvasitoje/edit?html,output
If you just remove 'ngAnimate' from the dependances, everything run well.

**Comment by simobasso** [comment]
Hi @soubok thanks for report!

**Comment by simobasso** [comment]
Hi @soubok, try this:

```
$scope.reloadRoute = function() {
  $animate.enabled(false);
  $route.reload();
  $timeout(function () {
    $animate.enabled(true);
  });
} 
```

**Comment by simobasso** [comment]
@soubok news?

**Comment by soubok** [comment]
Hi @simobasso, it works as expected (but it seems a little hacky no ?)

**Comment by simobasso** [comment]
Yes. It's a workaround. I don't know where is the problem.

**Comment by sayanee** [comment]
This issue is more than 3 months old and there hasn't been much activity on it. Closing, but please re-open it with a pull request on the bug 🤗
