### ISSUE TITLE
Had to change pdf to pdf-canvas for example to work

### ISSUE THREAD

**Issue by dereklin** [sayanee/angularjs-pdf#75]
I was trying out the example.  I had to change
```
<canvas id="pdf" class="rotate0"></canvas>
```
to
```
<canvas id="pdf-canvas" class="rotate0"></canvas>
```
for the code to work

**Comment by simobasso** [comment]
Hi @dereklin thanks for the report.

do you have set the attribute `canvasid` on your directive like this?

```
<ng-pdf template-url="partials/viewer.html" canvasid="pdf" scale="page-fit" page=13></ng-pdf>
```

**Comment by dereklin** [comment]
@simobasso my directive usage is just: 
```
<ng-pdf template-url="/partials/viewer.html"></ng-pdf>
```

**Comment by simobasso** [comment]
`canvasid` have as default `pdf-canvas`, if you want ovveride it you can do it as attribute `canvasid` in directive `ng-pdf`

What example have you look?

## Getting Started 
use this `canvas`:
```
<canvas id="pdf-canvas"></canvas>
```

## Code Example
use this `directive`:
```
<ng-pdf template-url="partials/viewer.html" canvasid="pdf" scale="page-fit" page=13></ng-pdf>
```

I hope this help you,
cheers
