### ISSUE TITLE
100% zoom not working after zooming in

### ISSUE THREAD

**Issue by dereklin** [sayanee/angularjs-pdf#76]
Go to http://sayan.ee/angularjs-pdf/
Zoom in a few times.  And then click on 100%.  Not thing happens.  I expected the page to go back to 100%.

**Comment by simobasso** [comment]
Hi @dereklin thanks for the report (again)!

yes, you are right.

Thx

**Comment by simobasso** [comment]
What do you think to submit a pull request?

**Comment by sayanee** [comment]
:+1:
