### ISSUE TITLE
Trying to implement this as a 'preview', server is returning pdf content, not a url... best way to implement

### ISSUE THREAD

**Issue by shannonfoster** [sayanee/angularjs-pdf#77]
I need to use this a a method to preview a working file and the backend hands me the pdf content rather than a url to the file.  How would I use this directive without a file path?

**Comment by sayanee** [comment]
Are you using `Unit8Array` then? See some instructions from the [pdf.js dependancy](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-specify-a-different-pdf-in-the-default-viewer)

**Comment by shannonfoster** [comment]
Thank you for the response.... is there an example I can follow?

**Comment by sayanee** [comment]
Could you try this [code snippet from another previous issue](https://github.com/sayanee/angularjs-pdf/issues/62#issuecomment-154835933) as suggested? He also wanted to use ` base64` or `Uint8Array`?

Seems like you need to create a blob:

```
currentBlob = new Blob([result], {type: 'application/pdf'});
$scope.pdfUrl = URL.createObjectURL(currentBlob);
```

**Comment by simobasso** [comment]
@shannonfoster it worked? we can add to Doc?

**Comment by sayanee** [comment]
:+1: yes i was also thinking of adding to the `readme.md`

**Comment by sayanee** [comment]
hi @shannonfoster - we added it to the [docs](https://github.com/sayanee/angularjs-pdf#when-url-is-base64-or-uint8array). Hope this solved your issue!

We are closing this issue, but please feel free to re-open and let us know the issue at hand :smile:
