### ISSUE TITLE
print pdf

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [sayanee/angularjs-pdf#78]
how print the pdf

**Comment by simobasso** [comment]
Hi @sidahmedbenkhaoua, 
at this time it isn't possible, but a pull request is welcome!

**Comment by simobasso** [comment]
@sidahmedbenkhaoua isn't possible print the pdf, but you can use `window.print()` to print the page.

To exclude other element you can use css's `@media print`.

Let me know!

**Comment by KranthiKishore** [comment]
Can someone suggest an angular gem for printing pdf?

**Comment by simobasso** [comment]
@KranthiKishore please, next time open an other issue, and open issue related to this package.

Gems are Ruby package, angular is JavaScript package.

**Comment by KranthiKishore** [comment]
@simobasso Sorry for that and Does this package supports pdf print?

**Comment by simobasso** [comment]
@KranthiKishore at this time isn't possible print the pdf, but you can use `window.print()` to print the page.

To exclude other element you can use css's `@media print`.
