### ISSUE TITLE
There is no way to set Authentication Header

### ISSUE THREAD

**Issue by gimoteco** [sayanee/angularjs-pdf#80]
When I get a pdf from secured source (through bearer token) I can't set a the requisition headers.

**Comment by simobasso** [comment]
hi @gimoteco, 
I hope [this](https://github.com/sayanee/angularjs-pdf/pull/60) help you!

**Comment by simobasso** [comment]
@gimoteco it worked? we can add to doc?

**Comment by gimoteco** [comment]
Thank you for your response, I'll test soon and if works I can put it in documentation.

**Comment by simobasso** [comment]
Thanks!

**Comment by gimoteco** [comment]
It's not clear to my, how can I set the configuration of my authentication (headers like token hash) using this attribute? (this attribute look like a on-off authentication).

**Comment by sayanee** [comment]
bf1f7de0a4195fa766315f3e7d929061a2e6eac0 Could you try the [branch code](https://github.com/sayanee/angularjs-pdf/tree/add-http-headers) to add the `http headers'? 

You can add it in the controller, example:

```
$scope.pdfUrl = 'pdf/relativity.pdf';
$scope.httpHeaders = {
     ...   
}
```

Here's a [similar example based on pdf.js](https://groups.google.com/forum/#!topic/mozilla.dev.pdf-js/iDUqbjMRcGc) or [an explanation](https://github.com/mozilla/pdf.js/issues/4082#issuecomment-31784231)

It seems we need to add `httpHeaders` by looking at the [current pdf.js source](https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L265):

```
* @property {string}     url   - The URL of the PDF.
 * @property {TypedArray|Array|string} data - Binary PDF data. Use typed arrays
 *   (Uint8Array) to improve the memory usage. If PDF data is BASE64-encoded,
 *   use atob() to convert it to a binary string first.
 * @property {Object}     httpHeaders - Basic authentication headers.
 * @property {boolean}    withCredentials - Indicates whether or not cross-site
 *   Access-Control requests should be made using credentials such as cookies
 *   or authorization headers. The default is false.
```

**Comment by gimoteco** [comment]
The first snippet worked for me, Is there anything that I could help you to put it on production?

**Comment by sayanee** [comment]
Thanks for checking @gimoteco - i will merge the branch code to master then.

Could you help me write the documentation by sending a pull request to `readme.md` ? :smile: Would be best written by someone who actually used it like you!

**Comment by sayanee** [comment]
@gimoteco please try the [latest release `v1.3.0`](https://github.com/sayanee/angularjs-pdf/releases/tag/1.3.0). Feel free to reopen this issue if there's any error.

**Comment by gimoteco** [comment]
It worked too!
