### ISSUE TITLE
Cookies of my web application are not sending along with the pdf get request.

### ISSUE THREAD

**Issue by abhilashpullelil** [sayanee/angularjs-pdf#88]
Hello,

My web application is using a cookie which is very important to render user reports. So, when I make request from angular-pdf, it is not sending the cookie to the server.

Is there any option to send cookie along with the request?

Or is there any work around for this problem?

Any help will be appreciated.

**Comment by sayanee** [comment]
How about [this](https://github.com/sayanee/angularjs-pdf/pull/60) and [this](https://github.com/mozilla/pdf.js/issues/4082)?

**Comment by abhilashpullelil** [comment]
Thanks for your quick response. I have managed to send cookie as well as authorization token via angular-pdf.

Thanks !!!
