### ISSUE TITLE
TypeError: Cannot read property 'getContext' of null

### ISSUE THREAD

**Issue by Taewa** [sayanee/angularjs-pdf#95]
Hello.

Basically what I want to do is that load a remote pdf through ionic modal.

I am using this url as a test
http://www.i-drain.net/userfiles/file/einbauanleitung_iboard.pdf

I followed this tutorial (but I do not need creating pdf. just load remote pdf)
http://gonehybrid.com/how-to-create-and-display-a-pdf-file-in-your-ionic-app/

**When I just launch ionic, I got this error**
`TypeError: Cannot read property 'getContext' of null
    at link (http://myIp:8100/lib/angular-pdf/dist/angular-pdf.js:50:25)
    at invokeLinkFn (http://myIp:8100/lib/ionic/js/ionic.bundle.js:17482:9)
    at nodeLinkFn (http://myIp:8100/lib/ionic/js/ionic.bundle.js:16982:11)
    at http://myIp:8100/lib/ionic/js/ionic.bundle.js:17212:13
    at processQueue (http://myIp:8100/lib/ionic/js/ionic.bundle.js:23399:28)
    at http://myIp:8100/lib/ionic/js/ionic.bundle.js:23415:27
    at Scope.$eval (http://myIp:8100/lib/ionic/js/ionic.bundle.js:24678:28)
    at Scope.$digest (http://myIp:8100/lib/ionic/js/ionic.bundle.js:24489:31)
    at Scope.$apply (http://myIp:8100/lib/ionic/js/ionic.bundle.js:24783:24)
    at done (http://myIp:8100/lib/ionic/js/ionic.bundle.js:19196:47) <ng-pdf ng-if="pdfUrl" template-url="partials/viewer.html" canvasid="pdf" scale="page-fit" style="display: block;">`

**A part of Controller**
`$scope.pdfUrl = "http://www.i-drain.net/userfiles/file/einbauanleitung_iboard.pdf";
        
    $ionicModal.fromTemplateUrl('/templates/modal-pdf.html', {
        scope: $scope,
        animation: 'slide-in-up'
    }).then(function(modal) {
        $scope.modal = modal;
    });`

**A part of modal-pdf.html**
`<ng-pdf ng-if="pdfUrl" template-url="partials/viewer.html" canvasid="pdf" scale="page-fit"></ng-pdf>`

**A part of viewer.html**
`<canvas id="pdf" class="rotate0"></canvas>`

I don't even know where to start to debug.
Any info will be helpful.
Thank you.

**Comment by Taewa** [comment]
`$scope.pdfUrl` was just in the controller and I moved it into `$scope.openModal` function.

**I got this error**
`XMLHttpRequest cannot load http://www.i-drain.net/userfiles/file/einbauanleitung_iboard.pdf. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://myIp' is therefore not allowed access.`

I tried with internal pdf file and it works fine.

So I guess it's going to work if I use my own api pdf file.

**Comment by simobasso** [comment]
Cross domain request it's not allowed by browser. 

You must use CORS in your server side. 

https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

I hope this help you! 

Cheers

**Comment by Taewa** [comment]
@simobasso 
Thank you for the answer.
I resolved with jsonp :)

**Comment by brettmeyer** [comment]
I'm having the same issue, but doesn't seem to be cross domain. Also getting the error:

`TypeError: Cannot read property 'getContext' of null`

Which I assume means it can't get the canvas.
Template file looks like this:

`<ng-pdf template-url="partials/viewer.html" canvasid="pdf-canvas" scale="page-fit"></ng-pdf>`

View looks like this:

`<canvas ng-if="pdfUrl" id="pdf-canvas" class="rotate0"></canvas>`

And lastly the controller:

`$ionicModal.fromTemplateUrl('templates/pdf-viewer.html', {
		scope: $scope,
		animation: 'slide-in-up'
	}).then(function (modal) {
		$scope.modal = modal;
	});

	$scope.viewPDF = function() {
		$scope.pdfUrl = 'http://localhost/commonproperty/bin/temp.pdf';
		$scope.modal.show();
	};`

Any help would be greatly appreciated!
