### ISSUE TITLE
Is there a way to highlight a particular string?

### ISSUE THREAD

**Issue by pudo** [sayanee/angularjs-pdf#96]
This library is a miracle for me, amazing work! I want to use it to display results for a search tool and ideally would want to support results highlighting. Is that possible?

**Comment by sayanee** [comment]
No this feature is not supported. 

Just did some quick search and you might find [an past example](http://vivin.net/2013/06/06/rendering-a-pdf-with-text-selection-using-pdf-js/) or a [discussion on pdf.js highlight text](https://github.com/mozilla/pdf.js/pull/5496) useful.

**Comment by pudo** [comment]
Thanks very much for the two pointers, very useful - happy to close the ticket unless you want to keep it as a feature request :)
