### ISSUE TITLE
Doesn't work when minified using yo angular build.

### ISSUE THREAD

**Issue by mbejda** [sayanee/angularjs-pdf#97]
Doesn't work when minified with `grunt build` generated by `yo angular`. I get the following error : 
```
Error: [$injector:modulerr] Failed to instantiate module pdf due to:
Error: [$injector:nomod] Module 'pdf' is not available!
```

Works just fine when its not minified.

**Comment by sayanee** [comment]
What is part of your unminified code to include it as a module in your project?

**Comment by mbejda** [comment]
The following are the steps to replicate the error : 
- yo angular app
- bower install angular-pdf --save
- Add the PDF.js CDN to the index.html (PDF.js does not minify nicely).
- grunt serve:dist

**Comment by mbejda** [comment]
Seems to wrong fine. There was a bug in a different library.
