### ISSUE TITLE
horizontal scroll not available

### ISSUE THREAD

**Issue by badpenguin** [sayanee/angularjs-pdf#98]
It worked out of the box!

But When i zoom the document the canvas can be scrolled only vertically and not horizzontally.

Is that a problem with the library? or Ionic?

I confirm that this does not work with android stock browser, chrome must be installed and for cordova the Xwalk engine must be used.

**Comment by sayanee** [comment]
Do you have sample code to replicate this?

**Comment by sayanee** [comment]
closing this - please feel free to reopen with sample code, steps to replicate it and a demo page.
